# Generated by Django 6.1.1 on 2026-09-30 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField()),
                (
                    "diet",
                    models.CharField(
                        choices=[
                            ("veg", "Vegetarian"),
                            ("non_veg", "Non-vegetarian"),
                            ("eggetarian", "Eggetarian"),
                            ("pescatarian", "Pescatarian"),
                            ("sattvik", "Sattvik"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cuisine", models.JSONField(default=list)),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
